In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import pathlib
import matplotlib.pyplot as plt

In [3]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.15.0-cp311-cp311-macosx_12_0_arm64.whl (2.1 kB)
Collecting tensorflow-macos==2.15.0 (from tensorflow)
  Downloading tensorflow_macos-2.15.0-cp311-cp311-macosx_12_0_arm64.whl (208.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 MB 4.5 MB/s eta 0:00:0000:0100:01
Collecting absl-py>=1.0.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 13.7 MB/s eta 0:00:00
Collecting astunparse>=1.6.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 6.3 MB/s eta 0:00:00
Requirement already satisfied: h5py>=2.9.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (3.7.0)
Collecting libclang>=13.0.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading libclang-16.0.6-py2.py3-none-macosx_11_0_arm64.whl (20.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 28.1 MB/s eta 0:00:0000:0100:01
Collecting ml-dtypes~=0.2.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading ml_dtypes-0.2.0-cp311-cp311-macosx_10_9_universal2.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 21.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.24.3)
Collecting opt-einsum>=2.3.2 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 9.4 MB/s eta 0:00:00
Requirement already satisfied: packaging in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (23.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading protobuf-4.25.2-cp37-abi3-macosx_10_9_universal2.whl (394 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.2/394.2 kB 18.7 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (67.8.0)
Requirement already satisfied: six>=1.12.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (4.6.3)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.15.0->tensorflow) (1.14.1)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading tensorflow_io_gcs_filesystem-0.34.0-cp311-cp311-macosx_12_0_arm64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 20.8 MB/s eta 0:00:00a 0:00:01
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading grpcio-1.60.0-cp311-cp311-macosx_10_10_universal2.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 9.2 MB/s eta 0:00:0000:0100:01m
Collecting tensorboard<2.16,>=2.15 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading tensorboard-2.15.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 27.5 MB/s eta 0:00:0000:0100:01
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 20.2 MB/s eta 0:00:00
Collecting keras<2.16,>=2.15.0 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 24.3 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow-macos==2.15.0->tensorflow) (0.38.4)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading google_auth-2.27.0-py2.py3-none-any.whl (186 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 186.8/186.8 kB 13.2 MB/s eta 0:00:00
Collecting google-auth-oauthlib<2,>=0.5 (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: markdown>=2.6.8 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (3.4.1)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-macos==2.15.0->tensorflow)
  Downloading protobuf-4.23.4-cp37-abi3-macosx_10_9_universal2.whl (400 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 23.7 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.21.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.29.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.2.3)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (0.2.8)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2023.5.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (2.1.1)

Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow) (0.4.8)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-macos==2.15.0->tensorflow)
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 16.5 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, opt-einsum, oauthlib, ml-dtypes, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-macos, tensorflow
Successfully installed absl-py-2.1.0 astunparse-1.6.3 cachetools-5.3.2 flatbuffers-23.5.26 gast-0.5.4 google-auth-2.27.0 google-auth-oauthlib-1.2.0 google-pasta-0.2.0 grpcio-1.60.0 keras-2.15.0 libclang-16.0.6 ml-dtypes-0.2.0 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.23.4 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.15.1 tensorboard-data-server-0.7.2 tensorflow-2.15.0 tensorflow-estimator-2.15.0 tensorflow-io-gcs-filesystem-0.34.0 tensorflow-macos-2.15.0 termcolor-2.4.0

In [4]:
# Importing Tensorflow

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)

2.15.0

In [5]:
!pip install git+https://github.com/tensorflow/docs # Use some functions from tensorflow_docs

Collecting git+https://github.com/tensorflow/docs
  Cloning https://github.com/tensorflow/docs to /private/var/folders/mr/4_bnkppx2f1d66x2rht3s1t40000gn/T/pip-req-build-o0my9t8r
  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/docs /private/var/folders/mr/4_bnkppx2f1d66x2rht3s1t40000gn/T/pip-req-build-o0my9t8r
  Resolved https://github.com/tensorflow/docs to commit d13c500b2e552ce04095287a99c575d2685a2160
  Preparing metadata (setup.py) ... done
Collecting astor (from tensorflow-docs==2024.1.17.4828)
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: absl-py in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-docs==2024.1.17.4828) (2.1.0)
Requirement already satisfied: jinja2 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-docs==2024.1.17.4828) (3.1.2)
Requirement already satisfied: nbformat in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-docs==2024.1.17.4828) (5.7.0)
Requirement already satisfied: protobuf>=3.12 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-docs==2024.1.17.4828) (4.23.4)
Requirement already satisfied: pyyaml in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from tensorflow-docs==2024.1.17.4828) (6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from jinja2->tensorflow-docs==2024.1.17.4828) (2.1.1)
Requirement already satisfied: fastjsonschema in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from nbformat->tensorflow-docs==2024.1.17.4828) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from nbformat->tensorflow-docs==2024.1.17.4828) (4.17.3)
Requirement already satisfied: jupyter-core in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from nbformat->tensorflow-docs==2024.1.17.4828) (5.3.0)
Requirement already satisfied: traitlets>=5.1 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from nbformat->tensorflow-docs==2024.1.17.4828) (5.7.1)
Requirement already satisfied: attrs>=17.4.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat->tensorflow-docs==2024.1.17.4828) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat->tensorflow-docs==2024.1.17.4828) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from jupyter-core->nbformat->tensorflow-docs==2024.1.17.4828) (3.11.0)
Building wheels for collected packages: tensorflow-docs
  Building wheel for tensorflow-docs (setup.py) ... done
  Created wheel for tensorflow-docs: filename=tensorflow_docs-2024.1.17.4828-py3-none-any.whl size=181250 sha256=a77f3208326a0e9b5b1717ec6e73acbdde522a0f7be85aa305833e1527f71135
  Stored in directory: /private/var/folders/mr/4_bnkppx2f1d66x2rht3s1t40000gn/T/pip-ephem-wheel-cache-nm21yow5/wheels/34/53/89/3db54cf97ce0f0261aaab3fdc12a847ea0879d34edf373e2c5
Successfully built tensorflow-docs
Installing collected packages: astor, tensorflow-docs
Successfully installed astor-0.8.1 tensorflow-docs-2024.1.17.4828

In [6]:
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

In [7]:
#plotly used for plotting Interactive Graphs
!pip install plotly
import plotly.offline as py
import plotly.express as px
import plotly.graph_objs as go

Requirement already satisfied: plotly in /Users/freyatran/anaconda3/lib/python3.11/site-packages (5.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /Users/freyatran/anaconda3/lib/python3.11/site-packages (from plotly) (8.2.2)

In [13]:
import pandas as pd
import os

In [16]:
dataset = pd.read_csv("final_data.csv")
dataset

      red  green  blue  label
0      20    139   240   Blue
1     174     83    72  Brown
2     144    249   131  Green
3     168     25   156   Pink
4      30    182   136  Green
...   ...    ...   ...    ...
5047   26     26    26  Black
5048   27     27    27  Black
5049   28     28    28  Black
5050   29     29    29  Black
5051   30     30    30  Black

[5052 rows x 4 columns]

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5052 entries, 0 to 5051
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   red     5052 non-null   int64
 1   green   5052 non-null   int64
 2   blue    5052 non-null   int64
 3   label   5052 non-null   object
dtypes: int64(3), object(1)
memory usage: 158.0+ KB

In [18]:
dataset.isnull().sum()

red      0
green    0
blue     0
label    0
dtype: int64

In [19]:
dataset.label.unique()

array(['Blue', 'Brown', 'Green', 'Pink', 'Yellow', 'Orange', 'Purple',
       'Red', 'Grey', 'White', 'Black'], dtype=object)

In [20]:
# One-Hot-Encoding
dataset = pd.get_dummies(dataset, columns=['label'])
dataset

,red,green,blue,label_Black,label_Blue,label_Brown,label_Green,label_Grey,label_Orange,label_Pink,label_Purple,label_Red,label_White,label_Yellow
0,20,139,240,0,1,0,0,0,0,0,0,0,0,0
1,174,83,72,0,0,1,0,0,0,0,0,0,0,0
2,144,249,131,0,0,0,1,0,0,0,0,0,0,0
3,168,25,156,0,0,0,0,0,0,1,0,0,0,0
4,30,182,136,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5047,26,26,26,1,0,0,0,0,0,0,0,0,0,0
5048,27,27,27,1,0,0,0,0,0,0,0,0,0,0
5049,28,28,28,1,0,0,0,0,0,0,0,0,0,0
5050,29,29,29,1,0,0,0,0,0,0,0,0,0,0
5051,30,30,30,1,0,0,0,0,0,0,0,0,0,0

In [21]:
dataset.columns
dataset = dataset[['red', 'green', 'blue', 'label_Red', 'label_Green', 'label_Blue', 'label_Yellow', 'label_Orange', 'label_Pink', 'label_Purple', 'label_Brown', 'label_Grey', 'label_Black', 'label_White']]
dataset

,red,green,blue,label_Red,label_Green,label_Blue,label_Yellow,label_Orange,label_Pink,label_Purple,label_Brown,label_Grey,label_Black,label_White
0,20,139,240,0,0,1,0,0,0,0,0,0,0,0
1,174,83,72,0,0,0,0,0,0,0,1,0,0,0
2,144,249,131,0,1,0,0,0,0,0,0,0,0,0
3,168,25,156,0,0,0,0,0,1,0,0,0,0,0
4,30,182,136,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5047,26,26,26,0,0,0,0,0,0,0,0,0,1,0
5048,27,27,27,0,0,0,0,0,0,0,0,0,1,0
5049,28,28,28,0,0,0,0,0,0,0,0,0,1,0
5050,29,29,29,0,0,0,0,0,0,0,0,0,1,0
5051,30,30,30,0,0,0,0,0,0,0,0,0,1,0

In [22]:
train_dataset = dataset.sample(frac=0.8, random_state=8) #train = 80%,  random_state = any int value means every time when you run your program you will get the same output for train and test dataset, random_state is None by default which means every time when you run your program you will get different output because of splitting between train and test varies within
test_dataset = dataset.drop(train_dataset.index) #remove train_dataset from dataframe to get test_dataset
#train_dataset

,red,green,blue,label_Red,label_Green,label_Blue,label_Yellow,label_Orange,label_Pink,label_Purple,label_Brown,label_Grey,label_Black,label_White
4185,189,148,192,0,0,0,0,0,0,1,0,0,0,0
3378,178,251,22,0,0,0,1,0,0,0,0,0,0,0
2744,54,9,125,0,0,1,0,0,0,0,0,0,0,0
968,119,147,60,0,1,0,0,0,0,0,0,0,0,0
2286,230,161,233,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,223,157,205,0,0,0,0,0,0,1,0,0,0,0
3707,203,8,10,1,0,0,0,0,0,0,0,0,0,0
881,154,153,123,0,0,0,0,0,0,0,0,1,0,0
1352,151,141,236,0,0,0,0,0,0,1,0,0,0,0
4552,236,222,32,0,0,0,1,0,0,0,0,0,0,0

In [31]:
train_labels = pd.DataFrame([train_dataset.pop(x) for x in ['label_Red', 'label_Green', 'label_Blue', 'label_Yellow', 'label_Orange', 'label_Pink', 'label_Purple', 'label_Brown', 'label_Grey', 'label_Black', 'label_White']]).T
train_labels

KeyError: 'label_Red'

In [29]:
train_dataset

      red  green  blue
4185  189    148   192
3378  178    251    22
2744   54      9   125
968   119    147    60
2286  230    161   233
...   ...    ...   ...
1883  223    157   205
3707  203      8    10
881   154    153   123
1352  151    141   236
4552  236    222    32

[4042 rows x 3 columns]

In [30]:
test_labels = pd.DataFrame([test_dataset.pop(x) for x in ['label_Red', 'label_Green', 'label_Blue', 'label_Yellow', 'label_Orange', 'label_Pink', 'label_Purple', 'label_Brown', 'label_Grey', 'label_Black', 'label_White']]).T
test_labels

,label_Red,label_Green,label_Blue,label_Yellow,label_Orange,label_Pink,label_Purple,label_Brown,label_Grey,label_Black,label_White
5,0,0,0,0,0,1,0,0,0,0,0
11,0,0,0,0,0,1,0,0,0,0,0
13,0,0,0,0,0,0,0,1,0,0,0
17,0,0,0,0,0,1,0,0,0,0,0
21,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
5042,0,0,0,0,0,0,0,0,0,1,0
5043,0,0,0,0,0,0,0,0,0,1,0
5046,0,0,0,0,0,0,0,0,0,1,0
5047,0,0,0,0,0,0,0,0,0,1,0
5050,0,0,0,0,0,0,0,0,0,1,0

In [35]:
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, kernel_regularizer=regularizers.l2(0.001), activation='relu', input_shape=[len(train_dataset.keys())]),
    Dense(24, kernel_regularizer=regularizers.l2(0.001), activation='relu'),
    Dense(24, kernel_regularizer=regularizers.l2(0.001), activation='relu'),
    Dense(16, kernel_regularizer=regularizers.l2(0.001), activation='relu'),
    Dense(11)
])

In [39]:
import tensorflow as tf

# Use the legacy Adam optimizer
optimizer = tf.keras.optimizers.legacy.Adam(learning_rate=0.001)

loss_function = tf.keras.losses.CategoricalCrossentropy(from_logits=True)

model.compile(
    loss=loss_function,
    optimizer=optimizer,
    metrics=['accuracy']
)

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 3)                 12

 dense_1 (Dense)             (None, 24)                96

 dense_2 (Dense)             (None, 24)                600

 dense_3 (Dense)             (None, 16)                400

 dense_4 (Dense)             (None, 11)                187

=================================================================
Total params: 1295 (5.06 KB)
Trainable params: 1295 (5.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [42]:
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling

history = model.fit(x=train_dataset, y=train_labels,
                    validation_split=0.2,
                    epochs=3000,
                    batch_size=2048,
                    verbose=0,
                    callbacks=[tfdocs.modeling.EpochDots()],
                    shuffle=True)

Epoch: 0, accuracy:0.0040,  loss:25.1684,  val_accuracy:0.0074,  val_loss:21.1830,
....................................................................................................
Epoch: 100, accuracy:0.6307,  loss:1.0519,  val_accuracy:0.6230,  val_loss:1.0673,
....................................................................................................
Epoch: 200, accuracy:0.7021,  loss:0.7752,  val_accuracy:0.6613,  val_loss:0.8060,
....................................................................................................
Epoch: 300, accuracy:0.7278,  loss:0.6923,  val_accuracy:0.6996,  val_loss:0.7195,
....................................................................................................
Epoch: 400, accuracy:0.7507,  loss:0.6362,  val_accuracy:0.7194,  val_loss:0.6591,
....................................................................................................
Epoch: 500, accuracy:0.7754,  loss:0.5801,  val_accuracy:0.7515,  val_loss:0.6100,
....................................................................................................
Epoch: 600, accuracy:0.8033,  loss:0.5268,  val_accuracy:0.7726,  val_loss:0.5568,
....................................................................................................
Epoch: 700, accuracy:0.8314,  loss:0.4582,  val_accuracy:0.8146,  val_loss:0.4890,
....................................................................................................
Epoch: 800, accuracy:0.8534,  loss:0.4181,  val_accuracy:0.8381,  val_loss:0.4482,
....................................................................................................
Epoch: 900, accuracy:0.8658,  loss:0.3857,  val_accuracy:0.8529,  val_loss:0.4197,
....................................................................................................
Epoch: 1000, accuracy:0.8685,  loss:0.3718,  val_accuracy:0.8566,  val_loss:0.4060,
....................................................................................................
Epoch: 1100, accuracy:0.8648,  loss:0.3672,  val_accuracy:0.8480,  val_loss:0.4065,
....................................................................................................
Epoch: 1200, accuracy:0.8667,  loss:0.3606,  val_accuracy:0.8504,  val_loss:0.3914,
....................................................................................................
Epoch: 1300, accuracy:0.8741,  loss:0.3460,  val_accuracy:0.8603,  val_loss:0.3768,
....................................................................................................
Epoch: 1400, accuracy:0.8701,  loss:0.3455,  val_accuracy:0.8653,  val_loss:0.3713,
....................................................................................................
Epoch: 1500, accuracy:0.8803,  loss:0.3241,  val_accuracy:0.8628,  val_loss:0.3578,
....................................................................................................
Epoch: 1600, accuracy:0.8825,  loss:0.3199,  val_accuracy:0.8591,  val_loss:0.3566,
....................................................................................................
Epoch: 1700, accuracy:0.8822,  loss:0.3184,  val_accuracy:0.8640,  val_loss:0.3474,
....................................................................................................
Epoch: 1800, accuracy:0.8815,  loss:0.3129,  val_accuracy:0.8752,  val_loss:0.3493,
....................................................................................................
Epoch: 1900, accuracy:0.8822,  loss:0.3103,  val_accuracy:0.8702,  val_loss:0.3423,
....................................................................................................
Epoch: 2000, accuracy:0.8800,  loss:0.3070,  val_accuracy:0.8677,  val_loss:0.3451,
....................................................................................................
Epoch: 2100, accuracy:0.8840,  loss:0.3063,  val_accuracy:0.8677,  val_loss:0.3395,
....................................................................................................
Epoch: 2200, accuracy:0.8815,  loss:0.3064,  val_accuracy:0.8665,  val_loss:0.3447,
....................................................................................................
Epoch: 2300, accuracy:0.8775,  loss:0.3116,  val_accuracy:0.8628,  val_loss:0.3488,
....................................................................................................
Epoch: 2400, accuracy:0.8840,  loss:0.3031,  val_accuracy:0.8714,  val_loss:0.3366,
....................................................................................................
Epoch: 2500, accuracy:0.8843,  loss:0.3120,  val_accuracy:0.8690,  val_loss:0.3517,
....................................................................................................
Epoch: 2600, accuracy:0.8828,  loss:0.3039,  val_accuracy:0.8677,  val_loss:0.3357,
....................................................................................................
Epoch: 2700, accuracy:0.8849,  loss:0.3035,  val_accuracy:0.8665,  val_loss:0.3344,
....................................................................................................
Epoch: 2800, accuracy:0.8825,  loss:0.3015,  val_accuracy:0.8690,  val_loss:0.3394,
....................................................................................................
Epoch: 2900, accuracy:0.8871,  loss:0.2970,  val_accuracy:0.8764,  val_loss:0.3337,
....................................................................................................

In [43]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()

          loss  accuracy  val_loss  val_accuracy  epoch
2995  0.301784  0.884318  0.338321      0.871446   2995
2996  0.299938  0.886792  0.333535      0.868974   2996
2997  0.298564  0.888648  0.336436      0.868974   2997
2998  0.296406  0.888958  0.348472      0.867738   2998
2999  0.302074  0.885864  0.337346      0.871446   2999

In [44]:
predictions = model.predict(test_dataset)

32/32 [==============================] - 0s 806us/step

In [48]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()

          loss  accuracy  val_loss  val_accuracy  epoch
2995  0.301784  0.884318  0.338321      0.871446   2995
2996  0.299938  0.886792  0.333535      0.868974   2996
2997  0.298564  0.888648  0.336436      0.868974   2997
2998  0.296406  0.888958  0.348472      0.867738   2998
2999  0.302074  0.885864  0.337346      0.871446   2999